### ISSUE TITLE
OpnSense/FreeBSD support?

### ISSUE THREAD

**Issue by vampywiz17** [database64128/swgp-go#14]
Hello there,

I try to set up wireguard over shadowsocks my opnsense firewall, but no luck... Now found this project and it is very interisting! It possible to use it with freebsd based system, like OPNsense?

**Comment by database64128** [comment]
Although I haven't tested it myself, it should work just fine on FreeBSD.

Speaking of Shadowsocks, you can check out my implementation of [Shadowsocks 2022](https://github.com/Shadowsocks-NET/shadowsocks-specs/blob/main/2022-1-shadowsocks-2022-edition.md): https://github.com/database64128/shadowsocks-go

**Comment by vampywiz17** [comment]
i will check it! Next question! this proxy use TCP? my main problem that one of enterprise network that my Wireguard is installed, blocked all UDP transit, only accept TCP 80/443 and similar ports...

**Comment by database64128** [comment]
TCP is not used, because it's such a terrible idea to proxy WireGuard traffic over TCP. Does your corporate firewall block 53/udp DNS traffic?

**Comment by vampywiz17** [comment]
@database64128 

Not checked yet. now i use 123/udp NTP . it work one of network segment, but the oders (Smartphones) not.
