### ISSUE TITLE
Proxy in TCP mode + documentation is not enough!

### ISSUE THREAD

**Issue by alpha856** [database64128/swgp-go#15]
Hello,
In some ISP's or countries most UDP connection ports are blocked. can you please develop proxy in TCP mode?
also i can't understand how to integrate proxy config with wireguard? can you please explain about config for clients and config for servers? you send only one sample config and i don't know this is for server only or client only or may seprate to using each other?

**Comment by database64128** [comment]
See https://github.com/database64128/swgp-go/discussions/11#discussioncomment-3290275. Basically you use `interfaces` on your "server" to run a proxy listener and points to your wg "server". On your "client" use `peers` to start a wg listener to accept packets from your wg "client" and forwards them to your proxy server.

Proxying UDP traffic over TCP is a terrible idea. What you are looking for is a proxy solution like Shadowsocks. Take a look at my implementation of [Shadowsocks 2022](https://github.com/Shadowsocks-NET/shadowsocks-specs/blob/main/2022-1-shadowsocks-2022-edition.md): https://github.com/database64128/shadowsocks-go

**Comment by jpmvferreira** [comment]
Allow me to hijack and say that I'm also interested in establishing a Wireguard connection when inside a very restrictive firewall, which among many things, blocks UDP traffic and I'm led to believe has deep package inspection.

Therefore, I would like to ask you:
1. If this project does not convert Wireguard's UDP packets to TCP, for obfuscation purposes, does Shadowsocks do it?
2. If converting UDP to TCP is such a bad idea, what would you suggest to bypass firewalls with these kind of restrictions?
