### ISSUE TITLE
Need x86-64 baseline version

### ISSUE THREAD

**Issue by Leozaki** [database64128/swgp-go#28]
log:
`This program can only be run on AMD64 processors with v2 microarchitecture support.
This program can only be run on AMD64 processors with v3 microarchitecture support.
`
cpu don't have these support.

**Comment by database64128** [comment]
Then you have to build your own binary. I don't think it's worth the extra CI time to build binaries for CPUs that are over 13 years old.

**Comment by Leozaki** [comment]
i think lots of virtual machines, nas, softwarebased-routers needs this..

**Comment by database64128** [comment]
> i think lots of virtual machines, nas, softwarebased-routers needs this..

That's clearly not the case. Even the worst VPS provider I've ever used has x86-64-v2.

ChaCha20-Poly1305 is designed for modern CPUs with wide vector instructions. If your CPU only has x86-64-v1, expect very low throughput.
