### ISSUE TITLE
"error": "the packet is larger than the supplied buffer"

### ISSUE THREAD

**Issue by azadrahorg** [database64128/swgp-go#34]
I installed the server and client, but when WireGuard is connected, the following error appears
can you help? Also, I set MTU at 1400

WARN service/client_mmsg.go:158 Failed to read from wgConn {"client": "client", "listenAddress": ":51822", "clientAddress": "
[::ffff:****]:51884", "packetLength": 1472, "error": "the packet is larger than the supplied buffer"}

**Comment by database64128** [comment]
If 1400 really is the actual PMTU between your swgp-go client and server, then you also need to reduce your WireGuard service's MTU down to the one suggested by swgp-go on startup.

If 1400 was just an arbitrary value you typed, you might want to increase it to match the actual PMTU.
