### ISSUE TITLE
Question about udp4 configuration for swgp-go

### ISSUE THREAD

**Issue by sergey-protsenko** [database64128/swgp-go#38]
Hello,

Is there a particular parameter in the configuration file to run server part of swgp-go to listen udp4 protocol? I see that on my machine (Ubuntu 22.04) it only listens to udp6 port.

Thank you.

**Comment by database64128** [comment]
Currently there's no such field in the config file for specifying the network string. It can be easily added though. In fact, it has already been done in my other project [shadowsocks-go](https://github.com/database64128/shadowsocks-go) when I added support for multiple listeners. But I'm not sure if it's really needed here at swgp-go. I have 2 questions for you:

1. What's the use case for only listening on the unspecified IPv4 address, when listening on the unspecified IPv6 address gives you dual-stack capability on almost all platforms?
2. Would it be useful for you to support multiple listeners per server/client?

**Comment by sergey-protsenko** [comment]
We can close this issue, I got answers on this question during work on another my issue with swgp-go.

Thank you for you help!

**Comment by database64128** [comment]
Being able to choose a custom network string can still be useful, and in general is just nice to have. So I added it: 03f35779b0b8f4c3c4270f1a04c1fceb65594608.
