### ISSUE TITLE
no route to host

### ISSUE THREAD

**Issue by ssrsec** [database64128/swgp-go#56]
wg-server:1.1.1.1

```
{
    "clients": [
        {
            "name": "client",
            "wgListen": ":20222",
            "wgFwmark": 0,
            "proxyEndpoint": "1.1.1.1:20220",
            "proxyMode": "zero-overhead",
            "proxyPSK": "5sNahkzMOXv/CfhE/hPbe5yp2MBo35fZdl1zm4Rd1T4=",
            "proxyFwmark": 0,
            "mtu": 1420
        }
    ]
}
```

```
{
    "servers": [
        {
            "name": "server",
            "proxyListen": ":20220",
            "proxyMode": "zero-overhead",
            "proxyPSK": "5sNahkzMOXv/CfhE/hPbe5yp2MBo35fZdl1zm4Rd1T4=",
            "proxyFwmark": 0,
            "wgEndpoint": "127.0.0.1:56093",
            "wgFwmark": 0,
            "mtu": 1420
        }
    ]
}
```

2024-09-15T00:14:09.681+0800 WARN service/client.go:515 Failed to write swgpPacket to proxyConn {"client": "client", "listenAddress": ":20222", "clientAddress": "[::ffff:127.0.0.1]:60684", "proxyAddress": "1.1.1.1:20220", "swgpPacketLength": 244, "error": "write udp [::]:55002->1.1.1.1:20220: sendto: no route to host"}

**Comment by ssrsec** [comment]
Does WG server have to support IPv6？

**Comment by database64128** [comment]
> write udp [::]:55002->1.1.1.1:20220: sendto: no route to host

This does not look right. It should be `[::ffff:1.1.1.1]:20220`, not `1.1.1.1:20220`. What OS are you running swgp-go on?

**Comment by database64128** [comment]
> Does WG server have to support IPv6？

No, the endpoint address can be a domain name, an IPv4 address, or an IPv6 address. All three address types are tested and supported.

**Comment by ssrsec** [comment]
### server

The IP address of this host is 1.1.1.1, and it is running the servers `wg` and `swgp-go`

wg0.conf:

```
[Interface]
PrivateKey = CNU9UfCMSeMYZNMX4vuX77SBaPzsauQatvt4gxhQO1k=
Address = 10.77.0.1/32 
PostUp   = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
ListenPort = 65431
DNS = 10.77.0.1
[Peer]
PublicKey = fc3+l2JqbG3cygjc1+7ncWZvCJlbwT0TiDv1OrF7KXI=
AllowedIPs = 10.77.0.2/24,127.0.0.1/32
```

server.json:
```
{
    "servers": [
        {
            "name": "server",
            "proxyListen": ":20220",
            "proxyMode": "zero-overhead",
            "proxyPSK": "5sNahkzMOXv/CfhE/hPbe5yp2MBo35fZdl1zm4Rd1T4=",
            "proxyFwmark": 0,
            "wgEndpoint": "[::1]:65431",
            "wgFwmark": 0,
            "mtu": 1420
        }
    ]
}
```


### client

This is my local computer, running the `wg` client and `swgp-go` client

wg.conf:
```
[Interface]
PrivateKey = UCtPUEQotx7VOqLheMdrB0X6b1Q0sNIT+L7aeQ7hWUQ=
Address = 10.77.0.2/24
DNS = 8.8.8.8
MTU = 1420

[Peer]
PublicKey = WyoTpynMJohbLDQBX0ioWY0lhg+bvIM25icikRVkpEk=
AllowedIPs = 0.0.0.0/1,::/0
Endpoint = 127.0.0.1:20222
PersistentKeepalive = 25
```


client.json:
```
{
    "clients": [
        {
            "name": "client",
            "wgListen": ":20222",
            "wgFwmark": 0,
            "proxyEndpoint": "[::ffff:1.1.1.1]:20220",
            "proxyMode": "zero-overhead",
            "proxyPSK": "5sNahkzMOXv/CfhE/hPbe5yp2MBo35fZdl1zm4Rd1T4=",
            "proxyFwmark": 0,
            "mtu": 1420
        }
    ]
}
```

### error msg

client msg:
```
2024-09-15T22:55:42.343+0800 INFO service/client.go:410 Client relay started {"client": "client", "listenAddress": ":20222", "clientAddress": "[::ffff:127.0.0.1]:60570", "proxyAddress": "[::ffff:1.1.1.1]:20220", "wgTunnelMTU": 1360}
2024-09-15T22:55:42.343+0800 WARN service/client.go:515 Failed to write swgpPacket to proxyConn {"client": "client", "listenAddress": ":20222", "clientAddress": "[::ffff:127.0.0.1]:60570", "proxyAddress": "[::ffff:1.1.1.1]:20220", "swgpPacketLength": 997, "error": "write udp [::]:50076->[::ffff:1.1.1.1]:20220: sendto: no route to host"}
```

Note: Neither server 1.1.1.1 nor my local computer has firewall enabled

**Comment by database64128** [comment]
There are quite a few problems in your configuration.

In `wg0.conf` on your server:

> AllowedIPs = 10.77.0.2/24,127.0.0.1/32

This is not right. `AllowedIPs` configures the peer's allowed source IP addresses inside the tunnel, and in the case of `wg-quick`, also sets up static routes to these prefixes. It definitely should not include `127.0.0.1/32`. In your case, it should be `AllowedIPs = 10.77.0.2/32`.

> DNS = 10.77.0.1

You don't need a DNS server on the server tunnel interface, unless you need it to resolve domain names to peer addresses inside the tunnel. This should not affect your use of the tunnel, but I would drop it if I were you.

In `server.json`:

> "mtu": 1420

The `"mtu"` field specifies the path MTU, not the tunnel interface MTU. If you live in China and use PPPoE with FTTH, this should be `1492`. Likewise, change it in `client.json`, but not in `wg.conf`.

In `wg.conf` on your client:

> AllowedIPs = 0.0.0.0/1,::/0

This could be the culprit. You specified a default route for IPv6, but didn't specify an IPv6 address on your tunnel interface. And `0.0.0.0/1` alone looks wrong. Change it to `AllowedIPs = 0.0.0.0/0` without the IPv6 route, if you don't care about IPv6.

To make sure swgp-go sends its traffic via your physical interface, while your WireGuard interface's default route is present, you have 2 options:

1. Add `Table = 1234` to `wg.conf` and assign the same number to `"proxyFwmark"` in `client.json`.
2. Specify your physical interface's IPv4 address in `"proxyConnListenAddress"` in `client.json`.

There could be more problems in your setup that I didn't spot. You might want to learn more about WireGuard and Linux's policy routing before you proceed.

**Comment by ssrsec** [comment]
感谢解答，但是问题还是没有解决。

我按照你的说明，已经修改了其他选项，但是关于你最后所提到的两个选项我不理解。

首先，`wg.conf`中并不支持`Table = 1234`这样的内容。

其次，在`client.json`中，我们这样配置`"proxyConnListenAddress": "127.0.0.1:52367"`正确吗，我不理解这个字段的作用


目前报错：

`error": "write udp 127.0.0.1:52367->1.1.1.1:20220: sendto: can't assign requested address`

**Comment by ssrsec** [comment]
我发现了一个问题，在客户端中，也就是我本机，我需要再开启一台虚拟机，确保wg-client和dtlspipe client在不同的主机上，然后在wg-client的conf文件中指向虚拟机的地址就可以正常使用了。

虽然目前解决了问题，但是很奇怪，这应该不是你们设计的方式，或许还是某些地方配置不对，我只是误打误撞成功了

**Comment by database64128** [comment]
> 首先，`wg.conf`中并不支持`Table = 1234`这样的内容。

Yes it does. See [`wg-quick(8)`](https://man.archlinux.org/man/wg-quick.8).

> 其次，在`client.json`中，我们这样配置`"proxyConnListenAddress": "127.0.0.1:52367"`正确吗，我不理解这个字段的作用
> 
> 目前报错：
> 
> `error": "write udp 127.0.0.1:52367->1.1.1.1:20220: sendto: can't assign requested address`

You want swgp-go to use your physical network interface's IPv4 address for outgoing traffic. It should be something like `"proxyConnListenAddress": "192.168.50.111:"`. Leave the port number unspecified so it can automatically choose a port.
